const ACTIONS = {
    SHARE_ROOMS: "SHARE_ROOMS",
    JOIN: "JOIN",
    LEAVE: "LEAVE",
    RELAY_SDP: "RELAY_SDP",
    RELAY_ICE: "RELAY_ICE",
    ICE_CANDIDATE: "ICE_CANDIDATE",
    ADD_PEER: "ADD_PEER",
    REMOVE_PEER: "REMOVE_PEER",
    SESSION_DESCRIPTION: "SESSION_DESCRIPTON",
}

module.exports = ACTIONS;